// GENERATED by tools/watch-emoji/gen-watch-emoji.mjs — DO NOT EDIT.
// Source: packages/ui/src/icons/stepIcons.ts
//
// Emoji images are 96x96 RGB565A8 LVGL binary images loaded at runtime
// from littlefs. This header carries ONLY the lookup table (a few KB of string
// data) — the pixel data stays in the littlefs partition, never in the app slot.
//
//   const char *p = rr_emoji_path(step->emoji);
//   if (p) lv_image_set_src(img, p); else /* fallback dot */;

#pragma once

#include <stddef.h>

#define RR_EMOJI_COUNT   150
#define RR_EMOJI_SIZE_PX 96
#define RR_EMOJI_MOUNT   "/lfs/emoji"

typedef struct {
    const char *emoji; /**< UTF-8 emoji exactly as stored in the DB / routine JSON */
    const char *path;  /**< LVGL filesystem path to the RGB565A8 binary image */
} rr_emoji_entry_t;

static const rr_emoji_entry_t RR_EMOJI_TABLE[RR_EMOJI_COUNT] = {
    { "🌅", RR_EMOJI_MOUNT "/1f305.bin" }, /* 1F305 — Morning */
    { "🌞", RR_EMOJI_MOUNT "/1f31e.bin" }, /* 1F31E — Morning */
    { "☀️", RR_EMOJI_MOUNT "/2600.bin" }, /* 2600 FE0F — Morning */
    { "🌤️", RR_EMOJI_MOUNT "/1f324.bin" }, /* 1F324 FE0F — Morning */
    { "🌄", RR_EMOJI_MOUNT "/1f304.bin" }, /* 1F304 — Morning */
    { "🛏️", RR_EMOJI_MOUNT "/1f6cf.bin" }, /* 1F6CF FE0F — Morning */
    { "⏰", RR_EMOJI_MOUNT "/23f0.bin" }, /* 23F0 — Morning */
    { "🕐", RR_EMOJI_MOUNT "/1f550.bin" }, /* 1F550 — Morning */
    { "⏱️", RR_EMOJI_MOUNT "/23f1.bin" }, /* 23F1 FE0F — Morning */
    { "🔔", RR_EMOJI_MOUNT "/1f514.bin" }, /* 1F514 — Morning */
    { "🐓", RR_EMOJI_MOUNT "/1f413.bin" }, /* 1F413 — Morning */
    { "🪥", RR_EMOJI_MOUNT "/1faa5.bin" }, /* 1FAA5 — Hygiene */
    { "🦷", RR_EMOJI_MOUNT "/1f9b7.bin" }, /* 1F9B7 — Hygiene */
    { "🧼", RR_EMOJI_MOUNT "/1f9fc.bin" }, /* 1F9FC — Hygiene */
    { "🧴", RR_EMOJI_MOUNT "/1f9f4.bin" }, /* 1F9F4 — Hygiene */
    { "🚿", RR_EMOJI_MOUNT "/1f6bf.bin" }, /* 1F6BF — Hygiene */
    { "🛁", RR_EMOJI_MOUNT "/1f6c1.bin" }, /* 1F6C1 — Hygiene */
    { "💧", RR_EMOJI_MOUNT "/1f4a7.bin" }, /* 1F4A7 — Hygiene */
    { "🧻", RR_EMOJI_MOUNT "/1f9fb.bin" }, /* 1F9FB — Hygiene */
    { "💅", RR_EMOJI_MOUNT "/1f485.bin" }, /* 1F485 — Hygiene */
    { "💈", RR_EMOJI_MOUNT "/1f488.bin" }, /* 1F488 — Hygiene */
    { "🪒", RR_EMOJI_MOUNT "/1fa92.bin" }, /* 1FA92 — Hygiene */
    { "🧽", RR_EMOJI_MOUNT "/1f9fd.bin" }, /* 1F9FD — Hygiene */
    { "👅", RR_EMOJI_MOUNT "/1f445.bin" }, /* 1F445 — Hygiene */
    { "💊", RR_EMOJI_MOUNT "/1f48a.bin" }, /* 1F48A — Hygiene */
    { "👕", RR_EMOJI_MOUNT "/1f455.bin" }, /* 1F455 — Getting_dressed */
    { "👖", RR_EMOJI_MOUNT "/1f456.bin" }, /* 1F456 — Getting_dressed */
    { "👗", RR_EMOJI_MOUNT "/1f457.bin" }, /* 1F457 — Getting_dressed */
    { "👚", RR_EMOJI_MOUNT "/1f45a.bin" }, /* 1F45A — Getting_dressed */
    { "👔", RR_EMOJI_MOUNT "/1f454.bin" }, /* 1F454 — Getting_dressed */
    { "🧥", RR_EMOJI_MOUNT "/1f9e5.bin" }, /* 1F9E5 — Getting_dressed */
    { "👟", RR_EMOJI_MOUNT "/1f45f.bin" }, /* 1F45F — Getting_dressed */
    { "👞", RR_EMOJI_MOUNT "/1f45e.bin" }, /* 1F45E — Getting_dressed */
    { "🥿", RR_EMOJI_MOUNT "/1f97f.bin" }, /* 1F97F — Getting_dressed */
    { "👢", RR_EMOJI_MOUNT "/1f462.bin" }, /* 1F462 — Getting_dressed */
    { "🧦", RR_EMOJI_MOUNT "/1f9e6.bin" }, /* 1F9E6 — Getting_dressed */
    { "🎒", RR_EMOJI_MOUNT "/1f392.bin" }, /* 1F392 — Getting_dressed */
    { "🧤", RR_EMOJI_MOUNT "/1f9e4.bin" }, /* 1F9E4 — Getting_dressed */
    { "🧢", RR_EMOJI_MOUNT "/1f9e2.bin" }, /* 1F9E2 — Getting_dressed */
    { "👒", RR_EMOJI_MOUNT "/1f452.bin" }, /* 1F452 — Getting_dressed */
    { "👓", RR_EMOJI_MOUNT "/1f453.bin" }, /* 1F453 — Getting_dressed */
    { "⌚", RR_EMOJI_MOUNT "/231a.bin" }, /* 231A — Getting_dressed */
    { "🍳", RR_EMOJI_MOUNT "/1f373.bin" }, /* 1F373 — Food___drink */
    { "🥚", RR_EMOJI_MOUNT "/1f95a.bin" }, /* 1F95A — Food___drink */
    { "🥣", RR_EMOJI_MOUNT "/1f963.bin" }, /* 1F963 — Food___drink */
    { "🥛", RR_EMOJI_MOUNT "/1f95b.bin" }, /* 1F95B — Food___drink */
    { "🍎", RR_EMOJI_MOUNT "/1f34e.bin" }, /* 1F34E — Food___drink */
    { "🍌", RR_EMOJI_MOUNT "/1f34c.bin" }, /* 1F34C — Food___drink */
    { "🍇", RR_EMOJI_MOUNT "/1f347.bin" }, /* 1F347 — Food___drink */
    { "🥕", RR_EMOJI_MOUNT "/1f955.bin" }, /* 1F955 — Food___drink */
    { "🥤", RR_EMOJI_MOUNT "/1f964.bin" }, /* 1F964 — Food___drink */
    { "🧃", RR_EMOJI_MOUNT "/1f9c3.bin" }, /* 1F9C3 — Food___drink */
    { "🍞", RR_EMOJI_MOUNT "/1f35e.bin" }, /* 1F35E — Food___drink */
    { "🥪", RR_EMOJI_MOUNT "/1f96a.bin" }, /* 1F96A — Food___drink */
    { "🥗", RR_EMOJI_MOUNT "/1f957.bin" }, /* 1F957 — Food___drink */
    { "🧀", RR_EMOJI_MOUNT "/1f9c0.bin" }, /* 1F9C0 — Food___drink */
    { "🍵", RR_EMOJI_MOUNT "/1f375.bin" }, /* 1F375 — Food___drink */
    { "🍽️", RR_EMOJI_MOUNT "/1f37d.bin" }, /* 1F37D FE0F — Food___drink */
    { "🍴", RR_EMOJI_MOUNT "/1f374.bin" }, /* 1F374 — Food___drink */
    { "🍪", RR_EMOJI_MOUNT "/1f36a.bin" }, /* 1F36A — Food___drink */
    { "🍕", RR_EMOJI_MOUNT "/1f355.bin" }, /* 1F355 — Food___drink */
    { "🍿", RR_EMOJI_MOUNT "/1f37f.bin" }, /* 1F37F — Food___drink */
    { "🏃", RR_EMOJI_MOUNT "/1f3c3.bin" }, /* 1F3C3 — Exercise */
    { "🤸", RR_EMOJI_MOUNT "/1f938.bin" }, /* 1F938 — Exercise */
    { "🧘", RR_EMOJI_MOUNT "/1f9d8.bin" }, /* 1F9D8 — Exercise */
    { "💪", RR_EMOJI_MOUNT "/1f4aa.bin" }, /* 1F4AA — Exercise */
    { "🏋️", RR_EMOJI_MOUNT "/1f3cb.bin" }, /* 1F3CB FE0F — Exercise */
    { "🚴", RR_EMOJI_MOUNT "/1f6b4.bin" }, /* 1F6B4 — Exercise */
    { "⚽", RR_EMOJI_MOUNT "/26bd.bin" }, /* 26BD — Exercise */
    { "🏀", RR_EMOJI_MOUNT "/1f3c0.bin" }, /* 1F3C0 — Exercise */
    { "🎾", RR_EMOJI_MOUNT "/1f3be.bin" }, /* 1F3BE — Exercise */
    { "🤾", RR_EMOJI_MOUNT "/1f93e.bin" }, /* 1F93E — Exercise */
    { "⛹️", RR_EMOJI_MOUNT "/26f9.bin" }, /* 26F9 FE0F — Exercise */
    { "🏊", RR_EMOJI_MOUNT "/1f3ca.bin" }, /* 1F3CA — Exercise */
    { "🤺", RR_EMOJI_MOUNT "/1f93a.bin" }, /* 1F93A — Exercise */
    { "🥋", RR_EMOJI_MOUNT "/1f94b.bin" }, /* 1F94B — Exercise */
    { "🛹", RR_EMOJI_MOUNT "/1f6f9.bin" }, /* 1F6F9 — Exercise */
    { "🏅", RR_EMOJI_MOUNT "/1f3c5.bin" }, /* 1F3C5 — Exercise */
    { "📚", RR_EMOJI_MOUNT "/1f4da.bin" }, /* 1F4DA — Learning */
    { "📖", RR_EMOJI_MOUNT "/1f4d6.bin" }, /* 1F4D6 — Learning */
    { "✏️", RR_EMOJI_MOUNT "/270f.bin" }, /* 270F FE0F — Learning */
    { "📝", RR_EMOJI_MOUNT "/1f4dd.bin" }, /* 1F4DD — Learning */
    { "🎨", RR_EMOJI_MOUNT "/1f3a8.bin" }, /* 1F3A8 — Learning */
    { "🖌️", RR_EMOJI_MOUNT "/1f58c.bin" }, /* 1F58C FE0F — Learning */
    { "🎵", RR_EMOJI_MOUNT "/1f3b5.bin" }, /* 1F3B5 — Learning */
    { "🎼", RR_EMOJI_MOUNT "/1f3bc.bin" }, /* 1F3BC — Learning */
    { "🎹", RR_EMOJI_MOUNT "/1f3b9.bin" }, /* 1F3B9 — Learning */
    { "🖥️", RR_EMOJI_MOUNT "/1f5a5.bin" }, /* 1F5A5 FE0F — Learning */
    { "🔬", RR_EMOJI_MOUNT "/1f52c.bin" }, /* 1F52C — Learning */
    { "🧮", RR_EMOJI_MOUNT "/1f9ee.bin" }, /* 1F9EE — Learning */
    { "🔢", RR_EMOJI_MOUNT "/1f522.bin" }, /* 1F522 — Learning */
    { "🌍", RR_EMOJI_MOUNT "/1f30d.bin" }, /* 1F30D — Learning */
    { "📐", RR_EMOJI_MOUNT "/1f4d0.bin" }, /* 1F4D0 — Learning */
    { "🧪", RR_EMOJI_MOUNT "/1f9ea.bin" }, /* 1F9EA — Learning */
    { "🧩", RR_EMOJI_MOUNT "/1f9e9.bin" }, /* 1F9E9 — Learning */
    { "🧹", RR_EMOJI_MOUNT "/1f9f9.bin" }, /* 1F9F9 — Chores */
    { "🗑️", RR_EMOJI_MOUNT "/1f5d1.bin" }, /* 1F5D1 FE0F — Chores */
    { "🧺", RR_EMOJI_MOUNT "/1f9fa.bin" }, /* 1F9FA — Chores */
    { "🪴", RR_EMOJI_MOUNT "/1fab4.bin" }, /* 1FAB4 — Chores */
    { "🐕", RR_EMOJI_MOUNT "/1f415.bin" }, /* 1F415 — Chores */
    { "🐈", RR_EMOJI_MOUNT "/1f408.bin" }, /* 1F408 — Chores */
    { "🛒", RR_EMOJI_MOUNT "/1f6d2.bin" }, /* 1F6D2 — Chores */
    { "🪣", RR_EMOJI_MOUNT "/1faa3.bin" }, /* 1FAA3 — Chores */
    { "📦", RR_EMOJI_MOUNT "/1f4e6.bin" }, /* 1F4E6 — Chores */
    { "🧯", RR_EMOJI_MOUNT "/1f9ef.bin" }, /* 1F9EF — Chores */
    { "🪑", RR_EMOJI_MOUNT "/1fa91.bin" }, /* 1FA91 — Chores */
    { "🧷", RR_EMOJI_MOUNT "/1f9f7.bin" }, /* 1F9F7 — Chores */
    { "♻️", RR_EMOJI_MOUNT "/267b.bin" }, /* 267B FE0F — Chores */
    { "🌙", RR_EMOJI_MOUNT "/1f319.bin" }, /* 1F319 — Evening */
    { "🌛", RR_EMOJI_MOUNT "/1f31b.bin" }, /* 1F31B — Evening */
    { "💤", RR_EMOJI_MOUNT "/1f4a4.bin" }, /* 1F4A4 — Evening */
    { "😴", RR_EMOJI_MOUNT "/1f634.bin" }, /* 1F634 — Evening */
    { "🛌", RR_EMOJI_MOUNT "/1f6cc.bin" }, /* 1F6CC — Evening */
    { "🧸", RR_EMOJI_MOUNT "/1f9f8.bin" }, /* 1F9F8 — Evening */
    { "📓", RR_EMOJI_MOUNT "/1f4d3.bin" }, /* 1F4D3 — Evening */
    { "📕", RR_EMOJI_MOUNT "/1f4d5.bin" }, /* 1F4D5 — Evening */
    { "🌟", RR_EMOJI_MOUNT "/1f31f.bin" }, /* 1F31F — Evening */
    { "⭐", RR_EMOJI_MOUNT "/2b50.bin" }, /* 2B50 — Evening */
    { "🕯️", RR_EMOJI_MOUNT "/1f56f.bin" }, /* 1F56F FE0F — Evening */
    { "🎮", RR_EMOJI_MOUNT "/1f3ae.bin" }, /* 1F3AE — Play */
    { "🎲", RR_EMOJI_MOUNT "/1f3b2.bin" }, /* 1F3B2 — Play */
    { "🃏", RR_EMOJI_MOUNT "/1f0cf.bin" }, /* 1F0CF — Play */
    { "🎭", RR_EMOJI_MOUNT "/1f3ad.bin" }, /* 1F3AD — Play */
    { "🎪", RR_EMOJI_MOUNT "/1f3aa.bin" }, /* 1F3AA — Play */
    { "🏰", RR_EMOJI_MOUNT "/1f3f0.bin" }, /* 1F3F0 — Play */
    { "🎠", RR_EMOJI_MOUNT "/1f3a0.bin" }, /* 1F3A0 — Play */
    { "🪀", RR_EMOJI_MOUNT "/1fa80.bin" }, /* 1FA80 — Play */
    { "🎯", RR_EMOJI_MOUNT "/1f3af.bin" }, /* 1F3AF — Play */
    { "🎸", RR_EMOJI_MOUNT "/1f3b8.bin" }, /* 1F3B8 — Play */
    { "🪁", RR_EMOJI_MOUNT "/1fa81.bin" }, /* 1FA81 — Play */
    { "🎺", RR_EMOJI_MOUNT "/1f3ba.bin" }, /* 1F3BA — Play */
    { "❤️", RR_EMOJI_MOUNT "/2764.bin" }, /* 2764 FE0F — Health */
    { "🩹", RR_EMOJI_MOUNT "/1fa79.bin" }, /* 1FA79 — Health */
    { "🌡️", RR_EMOJI_MOUNT "/1f321.bin" }, /* 1F321 FE0F — Health */
    { "🧠", RR_EMOJI_MOUNT "/1f9e0.bin" }, /* 1F9E0 — Health */
    { "🥦", RR_EMOJI_MOUNT "/1f966.bin" }, /* 1F966 — Health */
    { "😊", RR_EMOJI_MOUNT "/1f60a.bin" }, /* 1F60A — Health */
    { "🦵", RR_EMOJI_MOUNT "/1f9b5.bin" }, /* 1F9B5 — Health */
    { "⚡", RR_EMOJI_MOUNT "/26a1.bin" }, /* 26A1 — Special */
    { "🏆", RR_EMOJI_MOUNT "/1f3c6.bin" }, /* 1F3C6 — Special */
    { "🌈", RR_EMOJI_MOUNT "/1f308.bin" }, /* 1F308 — Special */
    { "🚀", RR_EMOJI_MOUNT "/1f680.bin" }, /* 1F680 — Special */
    { "✨", RR_EMOJI_MOUNT "/2728.bin" }, /* 2728 — Special */
    { "💫", RR_EMOJI_MOUNT "/1f4ab.bin" }, /* 1F4AB — Special */
    { "🦄", RR_EMOJI_MOUNT "/1f984.bin" }, /* 1F984 — Special */
    { "🎁", RR_EMOJI_MOUNT "/1f381.bin" }, /* 1F381 — Special */
    { "🌻", RR_EMOJI_MOUNT "/1f33b.bin" }, /* 1F33B — Special */
    { "🌸", RR_EMOJI_MOUNT "/1f338.bin" }, /* 1F338 — Special */
    { "🦋", RR_EMOJI_MOUNT "/1f98b.bin" }, /* 1F98B — Special */
    { "🎉", RR_EMOJI_MOUNT "/1f389.bin" }, /* 1F389 — Special */
};

/** Exact UTF-8 match on the stored emoji. Returns NULL if unmapped. */
static inline const char *rr_emoji_path(const char *emoji)
{
    if (emoji == NULL) return NULL;
    for (size_t i = 0; i < RR_EMOJI_COUNT; i++) {
        const char *a = emoji, *b = RR_EMOJI_TABLE[i].emoji;
        while (*a && *a == *b) { a++; b++; }
        if (*a == '\0' && *b == '\0') return RR_EMOJI_TABLE[i].path;
    }
    return NULL;
}
