// GENERATED by tools/watch-audio/gen-watch-audio.mjs — DO NOT EDIT.
//
// Pre-baked audio for the watch (spec §10B.3), 1 ch @ 22050 Hz — the
// ES8311/I2S BSP default, so nothing is ever resampled.
//
// ONE ENCODING, ONE PATH. Every clip is WAV PCM s16le and streams straight to
// the I2S DMA ring. The IMA ADPCM voice set is gone (see the generator header:
// pre-rendered speech cannot cover free-text step labels), and with it the only
// reason rr_audio ever had a second decoder.
//
// This header carries ONLY the lookup table. The PCM lives in the littlefs
// partition, never in the app slot.
//
//   rr_audio_play_tone(RR_TONE_STEP_DONE);
//   rr_audio_play_alarm();              /* preempts — see rr_audio.h */

#pragma once

#include <stddef.h>

#define RR_AUDIO_MOUNT      "/lfs/audio"
#define RR_AUDIO_RATE_HZ    22050
#define RR_AUDIO_BITS       16
#define RR_AUDIO_CHANNELS   1
#define RR_AUDIO_TONE_COUNT  6

typedef enum {
    RR_TONE_ALARM = 0,
    RR_TONE_ROUTINE_START = 1,
    RR_TONE_STEP_DONE = 2,
    RR_TONE_XP_CHIME = 3,
    RR_TONE_ROUTINE_COMPLETE = 4,
    RR_TONE_STEP_TARGET = 5,
} rr_tone_id_t;

static const char *const RR_TONE_TABLE[RR_AUDIO_TONE_COUNT] = {
    RR_AUDIO_MOUNT "/tone_alarm.wav",
    RR_AUDIO_MOUNT "/tone_routine_start.wav",
    RR_AUDIO_MOUNT "/tone_step_done.wav",
    RR_AUDIO_MOUNT "/tone_xp_chime.wav",
    RR_AUDIO_MOUNT "/tone_routine_complete.wav",
    RR_AUDIO_MOUNT "/tone_step_target.wav",
};

static inline const char *rr_audio_tone_path(rr_tone_id_t id)
{
    if ((size_t)id >= RR_AUDIO_TONE_COUNT) return NULL;
    return RR_TONE_TABLE[id];
}
