// GENERATED by tools/watch-audio/gen-watch-audio.mjs — DO NOT EDIT.
//
// Pre-baked audio for the watch (spec §10B.3). Clips are WAV PCM s16le,
// 1 ch, 22050 Hz — the ES8311/I2S BSP default, so they stream to the
// I2S DMA ring with no decode and no resample.
//
// This header carries ONLY the lookup tables. The PCM lives in the littlefs
// partition, never in the app slot.
//
//   const char *p = rr_audio_voice_path(step->label, child_lang);
//   if (p) rr_audio_play_file(p);
//   else   rr_audio_play_tone(RR_TONE_STEP_DONE);   /* no clip for custom labels */
//
// ⚠️ COVERAGE: voice prompts exist ONLY for the hardcoded starter-template
// labels. template_step.label is free text a parent types, so a custom step
// will MISS this table. The tone fallback above is mandatory, not optional.

#pragma once

#include <stddef.h>

#define RR_AUDIO_MOUNT      "/lfs/audio"
#define RR_AUDIO_RATE_HZ    22050
#define RR_AUDIO_BITS       16
#define RR_AUDIO_CHANNELS   1
#define RR_AUDIO_VOICE_COUNT 36
#define RR_AUDIO_TONE_COUNT  5

typedef enum {
    RR_TONE_ALARM = 0,
    RR_TONE_ROUTINE_START = 1,
    RR_TONE_STEP_DONE = 2,
    RR_TONE_XP_CHIME = 3,
    RR_TONE_ROUTINE_COMPLETE = 4,
} rr_tone_id_t;

typedef struct {
    const char *label; /**< starter-template label, matched against step->label */
    const char *lang;  /**< "en" | "el" — from child.language */
    const char *path;
} rr_voice_entry_t;

static const char *const RR_TONE_TABLE[RR_AUDIO_TONE_COUNT] = {
    RR_AUDIO_MOUNT "/tone_alarm.wav",
    RR_AUDIO_MOUNT "/tone_routine_start.wav",
    RR_AUDIO_MOUNT "/tone_step_done.wav",
    RR_AUDIO_MOUNT "/tone_xp_chime.wav",
    RR_AUDIO_MOUNT "/tone_routine_complete.wav",
};

static const rr_voice_entry_t RR_VOICE_TABLE[RR_AUDIO_VOICE_COUNT] = {
    { "Get Up", "en", RR_AUDIO_MOUNT "/voice_en_get_up.wav" },
    { "Get Up", "el", RR_AUDIO_MOUNT "/voice_el_get_up.wav" },
    { "Toilet", "en", RR_AUDIO_MOUNT "/voice_en_toilet.wav" },
    { "Toilet", "el", RR_AUDIO_MOUNT "/voice_el_toilet.wav" },
    { "Brush Teeth", "en", RR_AUDIO_MOUNT "/voice_en_brush_teeth.wav" },
    { "Brush Teeth", "el", RR_AUDIO_MOUNT "/voice_el_brush_teeth.wav" },
    { "Get Dressed", "en", RR_AUDIO_MOUNT "/voice_en_get_dressed.wav" },
    { "Get Dressed", "el", RR_AUDIO_MOUNT "/voice_el_get_dressed.wav" },
    { "Bag & Shoes", "en", RR_AUDIO_MOUNT "/voice_en_bag_shoes.wav" },
    { "Bag & Shoes", "el", RR_AUDIO_MOUNT "/voice_el_bag_shoes.wav" },
    { "Bath", "en", RR_AUDIO_MOUNT "/voice_en_bath.wav" },
    { "Bath", "el", RR_AUDIO_MOUNT "/voice_el_bath.wav" },
    { "Pyjamas", "en", RR_AUDIO_MOUNT "/voice_en_pyjamas.wav" },
    { "Pyjamas", "el", RR_AUDIO_MOUNT "/voice_el_pyjamas.wav" },
    { "Read", "en", RR_AUDIO_MOUNT "/voice_en_read.wav" },
    { "Read", "el", RR_AUDIO_MOUNT "/voice_el_read.wav" },
    { "Lights Out", "en", RR_AUDIO_MOUNT "/voice_en_lights_out.wav" },
    { "Lights Out", "el", RR_AUDIO_MOUNT "/voice_el_lights_out.wav" },
    { "Unpack Bag", "en", RR_AUDIO_MOUNT "/voice_en_unpack_bag.wav" },
    { "Unpack Bag", "el", RR_AUDIO_MOUNT "/voice_el_unpack_bag.wav" },
    { "Task 1", "en", RR_AUDIO_MOUNT "/voice_en_task_1.wav" },
    { "Task 1", "el", RR_AUDIO_MOUNT "/voice_el_task_1.wav" },
    { "Task 2", "en", RR_AUDIO_MOUNT "/voice_en_task_2.wav" },
    { "Task 2", "el", RR_AUDIO_MOUNT "/voice_el_task_2.wav" },
    { "Pack Bag", "en", RR_AUDIO_MOUNT "/voice_en_pack_bag.wav" },
    { "Pack Bag", "el", RR_AUDIO_MOUNT "/voice_el_pack_bag.wav" },
    { "Tidy Room", "en", RR_AUDIO_MOUNT "/voice_en_tidy_room.wav" },
    { "Tidy Room", "el", RR_AUDIO_MOUNT "/voice_el_tidy_room.wav" },
    { "Vacuum", "en", RR_AUDIO_MOUNT "/voice_en_vacuum.wav" },
    { "Vacuum", "el", RR_AUDIO_MOUNT "/voice_el_vacuum.wav" },
    { "Dishes", "en", RR_AUDIO_MOUNT "/voice_en_dishes.wav" },
    { "Dishes", "el", RR_AUDIO_MOUNT "/voice_el_dishes.wav" },
    { "well_done", "en", RR_AUDIO_MOUNT "/voice_en_well_done.wav" },
    { "well_done", "el", RR_AUDIO_MOUNT "/voice_el_well_done.wav" },
    { "all_done", "en", RR_AUDIO_MOUNT "/voice_en_all_done.wav" },
    { "all_done", "el", RR_AUDIO_MOUNT "/voice_el_all_done.wav" },
};

static inline const char *rr_audio_tone_path(rr_tone_id_t id)
{
    if ((size_t)id >= RR_AUDIO_TONE_COUNT) return NULL;
    return RR_TONE_TABLE[id];
}

/** Exact match on (label, lang). Returns NULL for custom labels — caller MUST
 *  fall back to a tone. */
static inline const char *rr_audio_voice_path(const char *label, const char *lang)
{
    if (label == NULL || lang == NULL) return NULL;
    for (size_t i = 0; i < RR_AUDIO_VOICE_COUNT; i++) {
        const char *a = label, *b = RR_VOICE_TABLE[i].label;
        while (*a && *a == *b) { a++; b++; }
        if (*a || *b) continue;
        const char *c = lang, *d = RR_VOICE_TABLE[i].lang;
        while (*c && *c == *d) { c++; d++; }
        if (*c == '\0' && *d == '\0') return RR_VOICE_TABLE[i].path;
    }
    return NULL;
}
