// GENERATED by tools/watch-emoji/gen-watch-emoji.mjs — DO NOT EDIT.
// Source: packages/ui/src/icons/stepIcons.ts
//
// Emoji images are 280x280 RGB565A8 LVGL binary images loaded at runtime
// from littlefs. This header carries ONLY the lookup table (a few KB of string
// data) — the pixel data stays in the littlefs partition, never in the app slot.
//
//   const char *p = rr_emoji_path(step->emoji);
//   if (p) lv_image_set_src(img, p); else /* fallback dot */;

#pragma once

#include <stddef.h>

#define RR_EMOJI_COUNT   6
#define RR_EMOJI_SIZE_PX 280
#define RR_EMOJI_MOUNT   "/lfs/emoji"

typedef struct {
    const char *emoji; /**< UTF-8 emoji exactly as stored in the DB / routine JSON */
    const char *path;  /**< LVGL filesystem path to the RGB565A8 binary image */
} rr_emoji_entry_t;

static const rr_emoji_entry_t RR_EMOJI_TABLE[RR_EMOJI_COUNT] = {
    { "🦁", RR_EMOJI_MOUNT "/1f981.bin" }, /* 1F981 — Avatar */
    { "🦊", RR_EMOJI_MOUNT "/1f98a.bin" }, /* 1F98A — Avatar */
    { "🐻", RR_EMOJI_MOUNT "/1f43b.bin" }, /* 1F43B — Avatar */
    { "🐰", RR_EMOJI_MOUNT "/1f430.bin" }, /* 1F430 — Avatar */
    { "🐼", RR_EMOJI_MOUNT "/1f43c.bin" }, /* 1F43C — Avatar */
    { "🦉", RR_EMOJI_MOUNT "/1f989.bin" }, /* 1F989 — Avatar */
};

/** Exact UTF-8 match on the stored emoji. Returns NULL if unmapped. */
static inline const char *rr_emoji_path(const char *emoji)
{
    if (emoji == NULL) return NULL;
    for (size_t i = 0; i < RR_EMOJI_COUNT; i++) {
        const char *a = emoji, *b = RR_EMOJI_TABLE[i].emoji;
        while (*a && *a == *b) { a++; b++; }
        if (*a == '\0' && *b == '\0') return RR_EMOJI_TABLE[i].path;
    }
    return NULL;
}
